### ISSUE TITLE
CTRL+C Causes Hang

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-NES#46]
Control + C causes the system to hang instead of exit.

```teraction Thread
[    0] [2021-05-17 06:36:00] [           Zookeeper] [   PrintDifferences] Node bg-turing-0 Connected
^CTraceback (most recent call last):
  File "Main.py", line 160, in <module>
    time.sleep(0.5) # <-- Sleep for a polling interval to avoid excessive CPU usage
KeyboardInterrupt
```

**Comment by datacrystals** [comment]
Identified that problem is most likely due to other processes not exiting when os._exit(1) is called.

**Comment by datacrystals** [comment]
Awesome, thank you so much Prishita! Please let me know if you need anything.

**Comment by PRISHIta123** [comment]
Apparently Ctrl-C causes it to hang and does not execute os._exit(1) as there is some other process holding on to the lock (but I am not sure which one it is).  

This is what I get after Ctrl-C again:
`^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:`

Also, in such a case what is order of the processes exiting from Main.py, there are four atexit.register decorated functions: 
CleanLog(), ShutdownZK(), ShutdownSockets() and a ForceExit() function. When is ForceExit() called, as I see the while loop running when its True, but nothing is executed when false (such as no function calls being made etc.)

**Comment by PRISHIta123** [comment]
There should be something within the while loop that tells the program what needs to be done specifically when a keyboard interrupt is encountered...

**Comment by datacrystals** [comment]
Hmm, thanks for looking into this. I'll go and try lumping the atexit calls into one function. One moment please...

**Comment by datacrystals** [comment]
Bingo... That seemed to be the right thing to do. Thanks so much for that great idea Prishita!

**Comment by PRISHIta123** [comment]
No problem, let me know if any other issue comes up, I'll try my best to help.

**Comment by datacrystals** [comment]
Thanks so much! I'll be sure to add you to the other issues that come up.
