### ISSUE TITLE
Create Global Version String

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-NES#53]
Create a proper versioning system, where all subsystems can read the version string from the main system to make sure updating versioning information is simple. 

Also update the MOTD to look better.

**Comment by PRISHIta123** [comment]
I can try to move the version information to a config file, such that all the programs can read from it and update accordingly, should I create one under /System/Config?

**Comment by datacrystals** [comment]
@PRISHIta123 

Apologies for the delay.

That could work however, that may not be the best way to do it, as the version string shouldn't be editable by the user. Perhaps if we put a python file in the Core directory under some path that makes sense that just contains the version as a variable? What do you think?

**Comment by PRISHIta123** [comment]
Sure I can try that, but for the version to be accessible across all files in all subdirectories, I will have to create it directly in the master branch instead of under Core.

**Comment by J-French1** [comment]
there is now a version variable in System/Core/VersionData.py
only thing left to do is find everything that uses the version data and redirect it

**Comment by datacrystals** [comment]
Apologies @PRISHIta123 for not getting back to you sooner. We worked on it today during the BG working session. Now, as @J-French1  said, we only need to go and replace any hardcoded ones with the new string system.

**Comment by PRISHIta123** [comment]
Replaced hardcoded version info in /System/Core/Management/API/ManagmentAPI.py . It was the only change that was required.

**Comment by datacrystals** [comment]
Awesome, Looks like this is resolved.
