### ISSUE TITLE
Write authentication system

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-NES#60]
Create authentication system for Management API Server.

**Comment by PRISHIta123** [comment]
This would use the same username and password for logging into the compute nodes right? There should be a database table with details of the core team members then, that can be looked up for write authentication

**Comment by datacrystals** [comment]
We could have it share username and password, however it's generally very inconvenient to have to create usernames and passwords on the machine, rather than having a separate database, so let's have our own database instead.

**Comment by PRISHIta123** [comment]
I have created a new branch for WriteAuthentication. The code will modify read/write/execute permissions based on whether the person who has logged in is the owner or is a member of the group (R/W/E), or is another external user (R only). We will have to create a core team group in each of the server systems by adding the members using groupadd manually, a demo is provided here: https://www.ibm.com/docs/en/ibm-mq/9.1?topic=windows-creating-managing-groups-linux

**Comment by datacrystals** [comment]
Hmm, I really want to make these systems independent, as I've never had good luck with Linux user management. Additionally, if we did it in the DB, we could have a permission for every command, so that new commands could be added and permissions assigned much more dynamically. 

I was thinking we'd have a function to add a new permission to the table (for when we initialize the system), and have one to check if that permission already exists. Then we can have one to modify a given user's permission of a certain command, and finally, one to check the permission of that given command. 

Does that sound like something we could do?

**Comment by PRISHIta123** [comment]
Do we have a table containing all possible commands to interface with the system? Each command can have its access specification in binary (R/W/E), the bgdb.user table could have an access specification for each user, then we can return possible commands a user could issue given if he is a member or not (members- R/W/E, others- R/E).

**Comment by datacrystals** [comment]
Unfortunately, we don't yet have the commands entered, hence why it would
be good for us to make a function to add the commands automatically.
Perhaps, if you make the command to enter the commands to the table, I can
add a system that looks through the code and auto detects the functions
available to the API. From there, it can assign permissions based on user
groups?

We could even make it simpler for the command, so rather than (R/W/E) it
could just be (CanRun/CannotRun).

Thanks so much for your help thus far.

**Comment by PRISHIta123** [comment]
I have updated the WriteAuthentication function in ManagementAPI.py to make use of Brad's command table for implementing the permissions (please check associated branch with same name). Brad has also created a pull request with the SQL modifications, so maybe the list of commands can be updated into the  bgdb.command table after his PR is merged. There is a function named updateCommand that I have defined for this purpose in ManagementAPI.py.

**Comment by datacrystals** [comment]
Perfect, thank you so much! I just merged Brad's branch, so we should be able to update the database now. I'm not sure how to run SQL scripts, so I'll leave that to you, but it's merged into the master branch now.

**Comment by PRISHIta123** [comment]
Do we have a function that automatically generates the list of possible commands that can be executed? I can use that to update the database.

**Comment by datacrystals** [comment]
Yeah, let me get on that right now. I've been working on other problems, Please give me a bit of time as I may not be able to finish it tonight. (It's 0:30 for me, so If I can't do it in the next hour or so, I'll have to pick it up tomorrow.)

If there's any other thing you can work on while I work on that, then that would probably be best for now. I'll reply here when I've gotten that command implemented.

**Comment by PRISHIta123** [comment]
No problem please take your time and let me know if you would require any help to implement it. Thanks!

**Comment by datacrystals** [comment]
Thank you so much Prishita! I don't think I'll finish it tonight, but I'll push my changes so you can see my work so far.

**Comment by datacrystals** [comment]
Done, please see branch dev-CreateCommandIndexingSystem.

I'll finish the rest of the command system tomorrow. Thanks for your patience.

**Comment by PRISHIta123** [comment]
I have completed the UpdateCommand function, but we need to manually enter the permission levels for each command in the table after executing the function. An additional function to assign permission levels to the users automatically also needs to be created.

**Comment by datacrystals** [comment]
Alright, sounds good. Are you able to keep the Tech spec up to date as well? 

I may be able to help more if I understand what's going on.

I'm, also having this issue when I try and run the code now:

```
Traceback (most recent call last):
  File "Main.py", line 117, in <module>
    sSocketAPI.UpdateCommand()
  File "/home/BrainGenix/System/Core/Management/API/ManagementAPI.py", line 394, in UpdateCommand
    cur.execute("INSERT INTO command (commandId,commandName) VALUES (%d, %s)",(index,self.CommandIndex[index]))
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 146, in execute
    query = self.mogrify(query, args)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 125, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: %d format: a number is required, not str
```

**Comment by datacrystals** [comment]
I've just pushed my changes so you can see if I borked anything up.

**Comment by PRISHIta123** [comment]
Oh I see I have to typecast the index, I was assuming that the dictionary keys were integers by default. One moment...

**Comment by datacrystals** [comment]
No problem, Let me know when you're done and I'll pull the changes and test them.

**Comment by PRISHIta123** [comment]
Yes I've updated it now.

**Comment by datacrystals** [comment]
Perfect, let me test it and get back to you.

**Comment by datacrystals** [comment]
Uh oh, looks like there's another problem:

```Traceback (most recent call last):
  File "Main.py", line 117, in <module>
    sSocketAPI.UpdateCommand()
  File "/home/BrainGenix/System/Core/Management/API/ManagementAPI.py", line 394, in UpdateCommand
    cur.execute("INSERT INTO command (commandId,commandName) VALUES (%d, %s)",(int(index),self.CommandIndex[index]))
ValueError: invalid literal for int() with base 10: 'mAPI_ls'```

**Comment by PRISHIta123** [comment]
Could you provide me an example key-value pair from the CommandIndex dictionary, I guess the index format is not the same as I am using to update the table...

**Comment by datacrystals** [comment]
Sure, I'll have it print out the Dictionary and provide you with that. I will have to run after that though, so I'll be back in a few hours.

**Comment by datacrystals** [comment]
```{'mAPI_ls': {}, 'mAPI_Version': {}, 'mAPI_TestAPI': {}, 'mAPI_RegenerateCommandIndex': {}, 'mAPI_License': {}, 'mAPI_Help': {}, 'LFTM': {'SystemTelemetryManager': {'mAPI_GetNodeStats': {}, 'mAPI_GetNodeList': {}, 'mAPI_GetClusterSize': {}, 'mAPI_GetAllNodeStats': {}}, 'SocketAPI': {'mAPI_ls': {}, 'mAPI_Version': {}, 'mAPI_TestAPI': {}, 'mAPI_RegenerateCommandIndex': {}, 'mAPI_License': {}, 'mAPI_Help': {}}}}```

**Comment by PRISHIta123** [comment]
Thanks I'll update the query according to this.

**Comment by datacrystals** [comment]
Awesome, Thanks.

**Comment by datacrystals** [comment]
Looks like there's still a problem here:
```
Traceback (most recent call last):
  File "Main.py", line 117, in <module>
    sSocketAPI.UpdateCommand()
  File "/home/BrainGenix/System/Core/Management/API/ManagementAPI.py", line 400, in UpdateCommand
    self.DBUpdate(self.DatabaseConfig, key)
  File "/home/BrainGenix/System/Core/Management/API/ManagementAPI.py", line 392, in DBUpdate
    cur.execute("INSERT INTO command (commandName) VALUES (%s)",(command))    
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1364, "Field 'permissionLevel' doesn't have a default value")```

**Comment by PRISHIta123** [comment]
I have added default values to the not null attributes of the user and command tables (check /Database/generateBrianDb.sql). You may have to delete these existing tables and re-run for the changes to take effect, if running it still returns the same error.

**Comment by datacrystals** [comment]
Oh ok I see thanks for that. How would I go about doing this? I apologize for the stupid question but I'm really not familiar with SQL. 

I'm assuming I drop the table but I'm not sure how to run the install SQL script.

**Comment by PRISHIta123** [comment]
Just run the BrainGenix system as you normally would, if it returns and errors, in that case you have to drop the user and command SQL tables, and just normally run the system again.

**Comment by PRISHIta123** [comment]
I have dropped the two tables in bg-turing0, you may have to check if it is working now (I am not able to run the system as the address is already in use, therefore cannot check)

**Comment by datacrystals** [comment]
Oh my bad. You should be able to run it now. I had left another instance running.

**Comment by PRISHIta123** [comment]
I have made some changes, I guess it should work properly now.

**Comment by datacrystals** [comment]
Oh no, is there an add user command for the DB? If not, it would probably make sense to make that part of the ACL System anyways.

**Comment by PRISHIta123** [comment]
I don't think anything is getting updated in the database tables inspite of using the pymysql queries, not the user or the commands (there isn't an add user function yet, it needs to be created). You could probably try running once to check if that's the case, as I found that no commands were added to the table from the UpdateCommand function...

**Comment by datacrystals** [comment]
Hmm, yeah if you wouldn't mind adding that function, that'd be great. If
not, we can also ask Brad to do it.

**Comment by datacrystals** [comment]
@PRISHIta123 any progress on this so far?

**Comment by PRISHIta123** [comment]
I have a few doubts about this. The config.yaml file only contains the default database login credentials, not the logged in users' credentials. There is no config file containing this information. Since we are using ssh to log into the main server port (braingenix.org) with our username and password, ssh generates a random authorization cookie for the user and stores it in a specific file format on the server, this is explained in more detail here: http://www.snapdba.com/2013/02/ssh-x-11-forwarding-and-magic-cookies/#.YOiqkOgzY2w

The random authentication cookie can then be written into the config.yaml file. 

The disadvantage of using the above method is that this cookie only remains active for the current user session, therefore, an entirely new BrainGenix database specific to this user will get created, there will not be a sharing of database tables among users, just one for each user, which gets destroyed after his/her session. It can be thought of as multiple users trying to share a machine, with no access to a common memory, who can only work on their allocated memory segment.

**Comment by datacrystals** [comment]
Right, perhaps I wasn't clear in my explanation, as I'm not super clear sometimes...

So the ACL system should look at the user database, and get the permissions from that. We don't need to even think about the users on the Linux system, as the purpose of this component is to replace the need to log in via ssh and do things there.

Are you able to come to the working call today? We may be able to clear this up faster there.

**Comment by PRISHIta123** [comment]
No problem, I will be available for the Sunday call (I wasn't able to attend the call yesterday due to the timing mismatch), will discuss it then.

**Comment by datacrystals** [comment]
Awesome, sounds good. Thanks so much!

**Comment by bkl4114** [comment]
Sorry, I'm coming to this late. We don't want to use the user table to log onto the database, just the application itself. The application would have the only connection to the db using its own credentials. Then we temporarily store who the user is and allow commands based upon that.

**Comment by PRISHIta123** [comment]
Thanks for these clarifications. I will create a pull request with the addUser function according to this.

**Comment by PRISHIta123** [comment]
I have generated pull request #74 with the function.

**Comment by datacrystals** [comment]
Thanks, I merged it, and I'll get back to you with any issues.
