### ISSUE TITLE
API causing connection drops

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-NES#62]
When running more than one node, the following error presents itself:

[    0] [2021-06-14 05:42:59] [          ManagementAPI] [ManagementAPIThread] Management API Recieved Connection From: ('127.0.0.1', 44810)
Connection dropped: socket connection broken
Transition to CONNECTING
[    9] [2021-06-14 05:44:02] [              Zookeeper] [  LeaderCheckDaemon] 
[    9] [2021-06-14 05:44:02] [        SystemTelemetry] [        AutoRefresh] Exception: 
Connection dropped: socket connection broken
Connection dropped: socket connection broken
Connection dropped: socket connection broken
Connection dropped: socket connection broken
Session has expired
[    9] [2021-06-14 05:44:08] [              Zookeeper] [  LeaderCheckDaemon] 
[    9] [2021-06-14 05:44:08] [              Zookeeper] [  LeaderCheckDaemon] 
[    9] [2021-06-14 05:44:08] [              Zookeeper] [  LeaderCheckDaemon] 
[    9] [2021-06-14 05:44:08] [              Zookeeper] [  LeaderCheckDaemon]

**Comment by PRISHIta123** [comment]
I am getting this error while trying to run the system directly, after the updates were made to the Management API Server: 

Traceback (most recent call last):
  File "Main.py", line 70, in <module>
    sSocketAPI = ManagementAPISocketServer(mLogger, ManagementAPIServerConfig, ZKConfigDict, mThreadManagerInstance)
  File "/home/BrainGenix/System/Core/Management/API/ManagementAPI.py", line 36, in __init__
    self.Socket.bind(self.SocketHost)
OSError: [Errno 98] Address already in use

**Comment by datacrystals** [comment]
Oh that was because the system running at the time, apologies for not
communicating that can happen. We really need to set up two dev servers so
that you can run day-to-day testing on one, and longer term testing on the
other.

**Comment by datacrystals** [comment]
Seems to be fixed for now with the rewrite using Kafka.
