### ISSUE TITLE
Brian2 generating pymysql Interface errors in DBUpdate

### ISSUE THREAD

**Issue by PRISHIta123** [carboncopies/BrainGenix-NES#80]
I encountered this error while running NES today, I have attached the screenshot below:

![image](https://user-images.githubusercontent.com/30746562/138553740-fe832aa9-9918-4cb8-9a74-6a13e1ba865e.png)

**Comment by datacrystals** [comment]
Let me know if it's working now.

**Comment by datacrystals** [comment]
Awesome, did that work for you? If not, we can figure something out on
Sunday.

**Comment by PRISHIta123** [comment]
I tried logging into two of the shared development servers (10.1.12.1, 10.1.13.1), however it is giving me a permission denied error when I am issuing my password.

**Comment by datacrystals** [comment]
Hmm, that's not good. I'll go take a look now. Sorry about that. I'll get
back to you when it's fixed.

**Comment by PRISHIta123** [comment]
I resolved this error by removing the code that closes the database connections. It seems to be working now.

**Comment by datacrystals** [comment]
Seems to be working for me as well - Thanks and sorry for the delay. I'll close this issue now, and feel free to reopen if needed.
