### ISSUE TITLE
Kafka Timeout Error

### ISSUE THREAD

**Issue by PRISHIta123** [carboncopies/BrainGenix-NES#84]
There is this new Kafka error due to a refused connection, I am not sure how to fix this  

![image](https://user-images.githubusercontent.com/30746562/140639230-fc594551-361c-4c5f-b79e-3cf418f2708a.png)

**Comment by datacrystals** [comment]
Huh, that's weird. I'll try rebooting the servers as I suspect something's
gone wrong there. If that doesn't work, then we can try debugging. Please
give me a few moments...

**Comment by PRISHIta123** [comment]
Yeah no problem please take your time

**Comment by datacrystals** [comment]
Alright, thanks for your patience, the servers should be up and running
now. Please let me know if the problem persists.

**Comment by PRISHIta123** [comment]
Yes Tom, it's working fine now. Thanks for all your help!

**Comment by datacrystals** [comment]
Fantastic, glad to hear it's working now.
